//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arara.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class locales
    {
        public locales()
        {
            this.orden = new HashSet<orden>();
            this.repartidor = new HashSet<repartidor>();
        }

        [RegularExpression(@"^[a-zA-Z0-9_ ]{3,10}?$")]
        [Required]
        [StringLength(10, ErrorMessage = "El ID debe tener entre 3 a 10 caracteres", MinimumLength = 3)]
        [Display(Name = "ID Local")]
        public string id_local { get; set; }

        [RegularExpression(@"^[a-zA-Z0-9_# ]{3,50}?$")]
        [Required]
        [StringLength(50, ErrorMessage = "El ID debe tener entre 3 a 50 caracteres", MinimumLength = 3)]
        [Display(Name = "ID Producto")]
        public string direccion { get; set; }

        [RegularExpression(@"^[a-zA-Z0-9_ ]{3,10}?$")]
        [Required]
        [StringLength(10, ErrorMessage = "El ID debe tener entre 3 a 10 caracteres", MinimumLength = 3)]
        [Display(Name = "ID Gerente [FK]")]
        public string id_gerente { get; set; }
    
        public virtual gerente gerente { get; set; }
        public virtual ICollection<orden> orden { get; set; }
        public virtual ICollection<repartidor> repartidor { get; set; }
    }
}
