//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arara.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlimentoVelozEntities1 : DbContext
    {
        public AlimentoVelozEntities1()
            : base("name=AlimentoVelozEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<gerente> gerente { get; set; }
        public DbSet<locales> locales { get; set; }
        public DbSet<orden> orden { get; set; }
        public DbSet<Productos> Productos { get; set; }
        public DbSet<repartidor> repartidor { get; set; }
    }
}
