//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arara.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Productos
    {

        [RegularExpression(@"^[a-zA-Z0-9_ ]{3,10}?$")]
        [Required]
        [StringLength(10, ErrorMessage = "El ID debe tener entre 3 a 10 caracteres", MinimumLength = 3)]
        [Display(Name = "ID Producto")]
        public string id_producto { get; set; }

        [RegularExpression(@"^[a-zA-Z0-9_ ]{3,20}?$")]
        [Required]
        [StringLength(20, ErrorMessage = "El ID debe tener entre 3 a 20 caracteres", MinimumLength = 3)]
        [Display(Name = "Nombre")]
        public string nombre { get; set; }

        [RegularExpression(@"^[a-zA-Z0-9_ ]{3,100}?$")]
        [Required]
        [StringLength(100, ErrorMessage = "El ID debe tener entre 3 a 10 caracteres", MinimumLength = 3)]
        [Display(Name = "Detalles")]
        public string detalles { get; set; }

        [RegularExpression(@"^[0-9.]{3,7}?$")]
        [Required]
        [StringLength(7, ErrorMessage = "El ID debe tener entre 3 a 7 caracteres", MinimumLength = 3)]
        [Display(Name = "Precio")]
        public double precio { get; set; }
    }
}
